# Generated by Django 5.0.1 on 2024-02-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="blockchain_address",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
