# Generated by Django 5.0.1 on 2024-02-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_blockchain_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
